# Generated by Django 3.2.6 on 2022-06-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(default='', max_length=255)),
                ('phnno', models.CharField(max_length=12)),
            ],
        ),
    ]
